### ISSUE TITLE
Another possible design: pre-loaded accounts

### ISSUE THREAD

**Issue by emschwartz** [interledgerjs/interfaucet#1]
If we use on-ledger transactions from the interfaucet, getting an account on the interledger will feel really slow (though it is pretty cool to fund accounts with IPRs and standard interledger payments). Another way we could go with this would be to have a website where you can select any of the supported cryptocurrencies and instantly get an account funded with testnet coins. You click a button to get your keypair (like on https://ripple.com/build/xrp-test-net/), get your credentials, and maybe even have an ILP client included in the page to send your first Interledger payment.

For XRP, we could use the same method that the testnet uses for generating credentials.
For ETH and BTC/LTC, I think the way to go would probably be to pre-generate credentials, fund them with testnet coins, and just have an API that gives you a pre-loaded account that's instantly ready to use. If we have the keys we could even be good testnet citizens and reclaim the funds from those accounts after 24 hours or so so we don't hog testnet coins.

Thoughts?

**Comment by justmoon** [comment]
I like it! I'd say it's probably not part of an MVP (keep in mind we have an OKR to get the Interfaucet up and running by the end of this month. But for a v2, this seems great, especially the part about being able to reclaim coins.

**Comment by michielbdejong** [comment]
> if we use on-ledger transactions, getting an account on the interledger will feel really slow

True, but that's also not what it's doing currently. The script used in tutorial 3 is for funding a btp address, see https://github.com/michielbdejong/ilp-node/blob/master/scripts/fund.js#L13.

We could give out pre-filled accounts on various testnets, but that would be more a multi-faucet than an interfaucet. I like the current setup where your funding payment goes to your BTP trustline at Amundsen, and from there you can make your first interledger payment.

> have an ILP client included in the page to send your first Interledger payment

That's a neat idea!

**Comment by michielbdejong** [comment]
Your suggestion to directly give out on-ledger funds instead of starting them out as trustline funds does maybe relate a bit to what we discussed yesterday about starting the first few tutorials with on-ledger escrow. But for that, you could also just start out with a payment from XRP to anywhere, since XRP wallets are born funded.

**Comment by emschwartz** [comment]
> funding payment goes to your BTP trustline at Amundsen, and from there you can make your first interledger payment.

The issue I see with this is that it feels like cheating. I don't think people will understand that Interledger connects different networks until you see real transfers going through on each ledger that correspond to the same Interledger payment.

> you could also just start out with a payment from XRP to anywhere, since XRP wallets are born funded.

Yup, but plenty of people aren't big fans of XRP and would be more into this whole thing if you could start from anywhere.

**Comment by emschwartz** [comment]
I wrote up https://github.com/interledger/interledger/issues/5 with my perspective on what types of experiences we should show off with the testnet of testnets and the Interfaucet

**Comment by michielbdejong** [comment]
> would be more into this whole thing if you could start from anywhere

OK, I agree that joining the testnet-of-testnets is not supereasy because joining >=1 testnets is a requirement, and the only testnet for which the faucet works painlessly is XRP.

I also agree it would be worth spending some of our time fixing that situation But then maybe we should just fix the existing faucets of those testnets and either upstream those contributions, or just tell people in those community "hey here's a faucet for you testnet that actually works, have fun wiht it"?

Something tells me that it's probably [not that simple](https://www.xkcd.com/1831/) but we could try.

Another option would be to show off Interledger in the process. Like, sure your faucet is hard to use, but here's one that works, only requirement is that you run a receiver on your on-ledger account and wait for a few minutes. And that's basically what we have now, right? I don't see merit in making the interfaucet be non-Interledgery.

To get back to your opening statement:

> getting an account on the interledger will feel really slow (though it is pretty cool to fund accounts with IPRs and standard interledger payments)

IMHO, compared to existing testnet faucets, waiting for any number of minutes up to say 60 minutes would be a good faucet experience. The only tough one is bitcoin maybe. But there we could just keep the pre-funded test accounts in a private wiki page and give them out as people come to https://gitter.im/interledger/testnet-of-testnets? And if in practice that happens more than once a week, we can still build that website to automates it later?

**Comment by michielbdejong** [comment]
Done, in the 'Testnet-of-testnets, sponsored infrastructure' page. Let me know if anyone needs access to it but doesn't have it.

**Comment by michielbdejong** [comment]
@emschwartz can this be closed?
